// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	pvz "avito/internal/domain/pvz"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreatePVZ provides a mock function with given fields: ctx, city
func (_m *Repository) CreatePVZ(ctx context.Context, city pvz.City) (*pvz.PVZ, error) {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for CreatePVZ")
	}

	var r0 *pvz.PVZ
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pvz.City) (*pvz.PVZ, error)); ok {
		return rf(ctx, city)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pvz.City) *pvz.PVZ); ok {
		r0 = rf(ctx, city)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pvz.PVZ)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pvz.City) error); ok {
		r1 = rf(ctx, city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPVZByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetPVZByID(ctx context.Context, id uuid.UUID) (*pvz.PVZ, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPVZByID")
	}

	var r0 *pvz.PVZ
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*pvz.PVZ, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *pvz.PVZ); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pvz.PVZ)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPVZs provides a mock function with given fields: ctx, startDate, endDate, city, page, limit
func (_m *Repository) GetPVZs(ctx context.Context, startDate *time.Time, endDate *time.Time, city *pvz.City, page int, limit int) ([]pvz.PVZWithReceptions, error) {
	ret := _m.Called(ctx, startDate, endDate, city, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPVZs")
	}

	var r0 []pvz.PVZWithReceptions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, *pvz.City, int, int) ([]pvz.PVZWithReceptions, error)); ok {
		return rf(ctx, startDate, endDate, city, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, *pvz.City, int, int) []pvz.PVZWithReceptions); ok {
		r0 = rf(ctx, startDate, endDate, city, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pvz.PVZWithReceptions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, *pvz.City, int, int) error); ok {
		r1 = rf(ctx, startDate, endDate, city, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
