// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	product "avito/internal/domain/product"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: ctx, productType, receptionID
func (_m *Repository) AddProduct(ctx context.Context, productType product.Type, receptionID uuid.UUID) (*product.Product, error) {
	ret := _m.Called(ctx, productType, receptionID)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 *product.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, product.Type, uuid.UUID) (*product.Product, error)); ok {
		return rf(ctx, productType, receptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, product.Type, uuid.UUID) *product.Product); ok {
		r0 = rf(ctx, productType, receptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, product.Type, uuid.UUID) error); ok {
		r1 = rf(ctx, productType, receptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLastProduct provides a mock function with given fields: ctx, receptionID
func (_m *Repository) DeleteLastProduct(ctx context.Context, receptionID uuid.UUID) error {
	ret := _m.Called(ctx, receptionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLastProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, receptionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProductsByReceptionID provides a mock function with given fields: ctx, receptionID
func (_m *Repository) GetProductsByReceptionID(ctx context.Context, receptionID uuid.UUID) ([]product.Product, error) {
	ret := _m.Called(ctx, receptionID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsByReceptionID")
	}

	var r0 []product.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]product.Product, error)); ok {
		return rf(ctx, receptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []product.Product); ok {
		r0 = rf(ctx, receptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, receptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
